[package]
authors = ["Giumo X. Clanjor (哆啦比猫/兰威举) <cjxgm@126.com>"]
name = "fancy-status"
version = "0.1.0"

[dependencies]
clap = "2.20"
time = "0.1"
fastup = { path = "fastup" }
color = { path = "color" }

[workspace]

[[bin]]
name = "fancy-status"
doc = false

