[package]
authors = ["Giumo X. Clanjor (哆啦比猫/兰威举) <cjxgm@126.com>"]
name = "fastup"
version = "0.1.0"
build = "build.rs"

[dependencies]
color = { path = "../color" }

[build-dependencies]
peg = "0.5"

