[package]
name = "stats-once"
version = "0.2.3"
authors = ["Giumo X. Clanjor (哆啦比猫/兰威举) <cjxgm@126.com>"]
publish = false     # This crate is actually an internal part of fancy-status.

[dependencies]
sysinfo = "0.8.2"
lazy_static = "1.3.0"

